server:
  port: 8301

spring:
  application:
    name: hello-service-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#helloService:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 500
  ReadTimeout: 600

helloService:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 900
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 700

logging:
  config: classpath:logback.xml
