server:
  port: 8301

spring:
  application:
    name: helloServiceConsumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#helloService:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true

logging:
  config: classpath:logback.xml
