server:
  port: 8701

spring:
  application:
    name: zuulService  # zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ribbon.eureka.enable=false  servserList= http://....,...
# openresty -> kong
zuul:
  routes:
    api-classic:
#      path: /nextclassic/**
#      url: http://localhost:8301
    api-next:
      path: /next/**
      serviceId: helloService
    api-consumer:
      path: /nextconsume/**
      serviceId: hello-service-consumer
  # /nextconsume/order/consumer/sayhello?message=next
  # /nextconsume/cinema/consumer?msg=next  窄化处理
  ignored-services: "*"

logging:
  config: classpath:logback.xml