server:
  port: 8701

spring:
  application:
    name: zuulService  # zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-next:
      path: /next/**
      serviceId: helloService
    api-consumer:
      path: /nextconsume/**
      serviceId: helloServiceConsumer

logging:
  config: classpath:logback.xml