server:
  port: 8800

spring:
  application:
    name: cinema

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh

username: aaa
password: bbb

logging:
  config: classpath:logback.xml
