server:
  port: 8900

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/woaijiadanoo/springconfig.git
          username: woaijiadanoo
          password: jiangzh_next@123
          basedir: ./config_server_demo/gitdata
#          repos:
#            cinema:
#              pattern: cinema/*
#              uri: https://github.com/woaijiadanoo/springcloud_config_spec.git
          search-paths: cinema
          clone-on-start: true

logging:
  config: classpath:logback.xml